//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fun.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingKnowledge
    {
        public TrainingKnowledge()
        {
            this.KnowledgeContexts = new HashSet<KnowledgeContext>();
            this.TrainingKnowlogeTerms = new HashSet<TrainingKnowlogeKeyWord>();
        }
    
        public int Id { get; set; }
        public int TrainingKnowledgeCategoryId { get; set; }
        public string Description { get; set; }
    
        public virtual TrainingKnowledgeCategory TrainingKnowledgeCategory { get; set; }
        public virtual ICollection<KnowledgeContext> KnowledgeContexts { get; set; }
        public virtual ICollection<TrainingKnowlogeKeyWord> TrainingKnowlogeTerms { get; set; }
    }
}
