//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fun.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingTermFeature
    {
        public TrainingTermFeature()
        {
            this.TrainingTermFetaurePositions = new HashSet<TrainingTermFetaurePosition>();
        }
    
        public int Id { get; set; }
        public string Letter { get; set; }
        public string TotalNumberOfThisLetter { get; set; }
        public int TrainingTermId { get; set; }
    
        public virtual TrainingTerm TrainingTerm { get; set; }
        public virtual ICollection<TrainingTermFetaurePosition> TrainingTermFetaurePositions { get; set; }
    }
}
