//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fun.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingKnowlogeKeyWord
    {
        public int Id { get; set; }
        public string Order { get; set; }
        public int TrainingTermId { get; set; }
        public int TrainingKnowledgeId { get; set; }
    
        public virtual TrainingTerm TrainingTerm { get; set; }
        public virtual TrainingKnowledge TrainingKnowledge { get; set; }
    }
}
