//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fun.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingTerm
    {
        public TrainingTerm()
        {
            this.TrainingTermFeatures = new HashSet<TrainingTermFeature>();
            this.TrainingKnowlogeTerms = new HashSet<TrainingKnowlogeKeyWord>();
        }
    
        public int Id { get; set; }
        public string Term { get; set; }
        public int LanguageCultureId { get; set; }
    
        public virtual ICollection<TrainingTermFeature> TrainingTermFeatures { get; set; }
        public virtual ICollection<TrainingKnowlogeKeyWord> TrainingKnowlogeTerms { get; set; }
        public virtual LanguageCulture LanguageCulture { get; set; }
    }
}
