//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fun.Entities.Designer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContextGrammerExpression
    {
        public int Id { get; set; }
        public int ContextGrammerRoleId { get; set; }
        public int RightContextTermId { get; set; }
    
        public virtual ContextGrammerRole ContextGrammerRole { get; set; }
        public virtual ContextTerm ContextTerm { get; set; }
    }
}
