//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fun.Entities.Designer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContextGrammerRole
    {
        public ContextGrammerRole()
        {
            this.ContextGrammerExpressions = new HashSet<ContextGrammerExpression>();
        }
    
        public int Id { get; set; }
        public int ContextGrammerId { get; set; }
        public int Nmber { get; set; }
        public int LeftContextTermId { get; set; }
    
        public virtual ContextGrammer ContextGrammer { get; set; }
        public virtual ContextTerm LeftContextTerm { get; set; }
        public virtual ICollection<ContextGrammerExpression> ContextGrammerExpressions { get; set; }
    }
}
