//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fun.Entities.Designer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContextGrammer
    {
        public ContextGrammer()
        {
            this.ContextGrammerRoles = new HashSet<ContextGrammerRole>();
        }
    
        public int Id { get; set; }
        public int TrainingKnowledgeCategoryId { get; set; }
    
        public virtual ICollection<ContextGrammerRole> ContextGrammerRoles { get; set; }
        public virtual TrainingKnowledgeCategory TrainingKnowledgeCategory { get; set; }
    }
}
