//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fun.Entities.Designer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingKnowledgeCategory
    {
        public TrainingKnowledgeCategory()
        {
            this.TrainingKnowledges = new HashSet<TrainingKnowledge>();
            this.ContextGrammers = new HashSet<ContextGrammer>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<TrainingKnowledge> TrainingKnowledges { get; set; }
        public virtual ICollection<ContextGrammer> ContextGrammers { get; set; }
    }
}
